mysql—url: jdbc:mysql://localhost:3306/onlinechat?useUnicode=true&characterEncoding=UTF-8
  &autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
spring:
  datasource:
    type:  com.zaxxer.hikari.HikariDataSource
    url: ${mysql-url}
    username: root
    password: root
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000        # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                  # 最小连接数
      maximum-pool-size: 20            # 最大连接数
      auto-commit: true                # 事务自动提交
      idle-timeout: 600000             # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000             # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1  # 连接测试语句

  flyway:
    enabled: true # 开启flyway
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
    clean-disabled: true
    locations: classpath:db/migration  #flyway文件目录
    table: flyway_schema_history  #历史表名
    baseline-on-migrate: true
    validate-on-migrate: true  #连续性校验
    baseline-version: 1 #指定默认版本
    encoding: UTF-8 #编码
    out-of-order: false # 是否允许不按顺序迁移 开发建议 true  生产建议 false
    sql-migration-prefix: V #前缀默认v
    sql-migration-separator: __ #分割符，默认__
    sql-migration-suffixes: .sql  #迁移文件，默认.sql


  redis:
    lettuce:
      pool:
        max-active: 128
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 10000
    host: 127.0.0.1
    port: 6379
    database: 0
    password: #密码


redis:
  timeout: 10000 #客户端超时时间单位是毫秒 默认是2000
  maxIdle: 300 #最大空闲数
  maxTotal: 1000 #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
  maxWaitMillis: 1000 #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  minEvictableIdleTimeMillis: 300000 #连接的最小空闲时间 默认1800000毫秒(30分钟)
  numTestsPerEvictionRun: 1024 #每次释放连接的最大数目,默认3
  timeBetweenEvictionRunsMillis: 30000 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  testOnBorrow: true #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testWhileIdle: true #在空闲时检查有效性, 默认false
  password:  #密码

jetcache:
  statIntervalMinutes: 1 #统计间隔
  areaInCacheName: false
  local:
    default: #默认area
      type: caffeine
      keyConvertor: fastjson
      limit: 10000              #本地缓存最大个数
      defaultExpireInMillis: 10000   #缓存的时间全局 默认值
  remote:
    default:
      type: redis.lettuce #使用lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 1
        maxIdle: 50
        maxTotal: 1000
        maxWait: 1000
      uri: redis://password@localhost:6379/0  #redis://密码@IP:端口/库


