##邮件通知设置
#spring:
#  mail:
#    host: smtp.163.com
#    username: shoppingkill@163.com
#    password: ATATHDCCTFQGRONE
#    port: 25
#    default-encoding: utf-8
#    protocol: smtp

# 阿里云存储参数配置
ali:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI4GJGi47WfwDsYhWwm4N5
    accessKeySecret: 0hHVEwE2FewGpsAUwqAFFfJFulsYA6
    bucketName: shoppingkill
    url: //shopingkill.oss-cn-shenzhen.aliyuncs.com/
    aliUrl: http://shopingkill.oss-cn-shenzhen.aliyuncs.com/
    getFileUrl: ${aliyun.oss.url}${aliyun.oss.fileDir}
    myHostUrl: http://static.wslhome.top/

#SMS榛子云参数配置
zzy:
  apiUrl: https://sms_developer.zhenzikj.com
  appSecret: NTNlN2M0ODItN2Q5OS00MmU4LTg1Y2EtZmM5NDMyZDMzMzZh
  appId: 105924

jwt:
  redisToken: 4800
  expire: 3600
  newToken: 600
  keys: wslhome-shoppingkill-sirwsl

verify:
  imgCodeTimeOut: 300
  phoneCodeTimeOut: 300

req:
  doMainUrl: wslhome.top

url:
  image: http://static.wslhome.top/
  webPage: http://test.wslhome.top/
  server: http://chatserver.wslhome.top/